services:
  database:
      container_name: sonco_db
      image: postgres
      environment:
        POSTGRES_DB: sonco
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass
      ports:
        - 5406:5432
  redis:
    container_name: sonco_redis
    image: "redis:alpine"
    command: redis-server --requirepass 1234560
    ports:
        - "6379:6379"
    volumes:
        - $PWD/local/redis-data:/var/lib/redis
        - $PWD/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
        - REDIS_REPLICATION_MODE=master

volumes:
  db-data:
    driver: local
