services:
  database:
      container_name: grid_filters_test
      image: postgres
      environment:
        POSTGRES_DB: grid_filters_test
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass
      ports:
        - 5432:5432
volumes:
  db-data:
    driver: local
